# https://github.com/ls-lint/docs

ls:
  # keep-sorted start
  .md: regex:^[A-Z][A-Z0-9]*$
  .rb: snake_case
  .sh: snake_case
  .yaml: kebab-case
  .yml: kebab-case
  # keep-sorted end

ignore:
  # keep-sorted start
  - .git
  - .github
  - node_modules
  - vendor
  # keep-sorted end
