name: Bats

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  bats:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats
      - name: Run bats tests
        run: |
          find . -name "*.bats" -print0 | while IFS= read -r -d '' test_file; do
            test_dir=$(dirname "$test_file")
            echo "Running $test_file from directory $test_dir"
            (cd "$test_dir" && bats "$(basename "$test_file")")
          done
